title: "Top Tarkovsky Movies"
description: "A collection of Andrei Tarkovsky's movies"
theme: jekyll-theme-minimal
logo: "/assets/images/logo.png"
author:
  name: "Pavel Charheika"
  email: "pc451309@students.mimuw.edu.pl"
paginate: 5
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
