title: "Top Tarkovsky Movies"
description: "A collection of Andrei Tarkovsky's movies"
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: default
author:
  name: "Pavel Charheika"
paginate: 5
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
